(function () {
  window.ACoordState = {
    currentStructure: null,
    currentSelectedAtom: null,
    currentSelectedBondKey: null,
    selectedAtomIds: [],
    isDragging: false,
    dragAtomId: null,
    adsorptionReferenceId: null,
    adsorptionAdsorbateIds: [],
    manualScale: 1,
    autoScaleEnabled: false,
    atomSizeScale: 1,
    bondThicknessScale: 1,
    viewZoom: 1,
    projectionMode: 'orthographic',
    scaleAtomsWithLattice: false,
    supercell: [1, 1, 1],
    unitCellEditing: false,
    renderAtomOffsets: {},
    shouldFitCamera: true,
    groupMoveActive: false,
    lastDragWorld: null,
    dragPlaneNormal: null,
    rotationAxis: 'z',
    rotationInProgress: false,
    // Display settings
    backgroundColor: '#0d1015',
    unitCellColor: '#FF6600',
    // Lighting settings
    lightingEnabled: true,
    ambientIntensity: 0.5,
    keyLight: { intensity: 0.8, x: 10, y: 10, z: 10 },
    fillLight: { intensity: 0, x: -10, y: -5, z: 5 },
    rimLight: { intensity: 0, x: 0, y: 5, z: -10 },
  };
})();
